name: Test Linux Install

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

    
jobs:
  test-setup:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fix conda environment
        run: |
          conda init bash
          conda config --set auto_activate_base false

      - name: Run setup.sh
        run: bash setup.sh
